# Generated by Django 2.2.5 on 2020-07-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='学生姓名')),
            ],
            options={
                'db_table': 'tb_student_info',
            },
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bcomment',
            field=models.IntegerField(default=0, help_text='评论量，默认为0,可不传', verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(default='', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(default=0, help_text='阅读量，默认为0,可不传', verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='booktest.BookInfo', verbose_name='图书'),
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='课程名字')),
                ('students', models.ManyToManyField(to='booktest.StudentInfo')),
            ],
            options={
                'db_table': 'tb_course_info',
            },
        ),
    ]
