# Generated by Django 2.2.5 on 2020-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='学生姓名')),
            ],
            options={
                'db_table': 'tb_student_info',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='课程名字')),
                ('students', models.ManyToManyField(to='ok.StudentInfo')),
            ],
            options={
                'db_table': 'tb_course_info',
            },
        ),
    ]
