# Generated by Django 2.2.5 on 2020-06-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='areas',
        ),
    ]
